# Generated by Django 3.1.4 on 2021-03-18 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código', max_length=150, null=True, unique=True, verbose_name='codigo')),
                ('nombre', models.CharField(help_text='Nombre', max_length=150, verbose_name='Nombre')),
                ('precio', models.DecimalField(blank=True, decimal_places=3, default=0, help_text='PRECIO NETO', max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70, verbose_name='Categoría')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_l', models.CharField(max_length=50, verbose_name='Localidad')),
                ('cp', models.CharField(max_length=20, verbose_name='Codigo Postal')),
                ('provincia', models.CharField(max_length=50)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='TipoMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
                ('autonumerico', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Unidad_medida')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Unidades de medida',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre/s')),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidad.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de carga', verbose_name='Fecha')),
                ('numero1', models.CharField(default='00001', help_text='Número', max_length=5)),
                ('numero', models.CharField(max_length=15)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Artículo', to='entidad.articulo')),
                ('cliente', models.ForeignKey(default='1', help_text='Nº de documento o CUIT del Tercero', limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.CASCADE, to='entidad.persona')),
                ('tipo', models.ForeignKey(help_text='Tipo de movimiento', on_delete=django.db.models.deletion.CASCADE, to='entidad.tipomovimiento', verbose_name='Tipo_movimiento')),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría', on_delete=django.db.models.deletion.CASCADE, to='entidad.categoria'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='unidad_de_medida',
            field=models.ForeignKey(help_text='Unidad de medida', on_delete=django.db.models.deletion.CASCADE, to='entidad.unidad_medida'),
        ),
    ]
